"""Provider-neutral configuration for recursive refinement.

The default recurrence retains six working-note updates followed by one candidate
update, repeated for three improvement steps per explicitly configured tier.
"""
from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Any, Callable


@dataclass(frozen=True)
class Tier:
    """An opaque, operator-selected model identifier; no capability is inferred."""
    model: str
    max_steps: int | None = None
    max_tokens: int = 2048
    step_timeout_s: float | None = None


DEFAULT_LADDER = (Tier("local"),)
RESEARCH_LADDER = DEFAULT_LADDER


@dataclass(frozen=True)
class Verdict:
    """A trusted check's result. A statistical/provisional pass is not a proof."""
    passed: bool
    settles_at: str | None = None
    note: str = ""
    confidence: float = 1.0

    def __post_init__(self) -> None:
        if type(self.passed) is not bool:
            raise TypeError("passed must be a bool")
        _number("confidence", self.confidence, minimum=0, maximum=1)
        if self.settles_at is not None:
            from datetime import date
            date.fromisoformat(self.settles_at)
        if not isinstance(self.note, str):
            raise TypeError("note must be a string")


Validator = Callable[[str], bool | Verdict]


def _integer(name: str, value: Any, minimum: int = 1) -> None:
    if type(value) is not int or value < minimum:
        raise ValueError(f"{name} must be an integer >= {minimum}")


def _number(name: str, value: Any, *, minimum: float = 0,
            maximum: float | None = None, strict: bool = False) -> None:
    if type(value) not in (int, float) or not math.isfinite(value):
        raise ValueError(f"{name} must be finite")
    if value < minimum or (strict and value == minimum):
        raise ValueError(f"{name} must be {'>' if strict else '>='} {minimum}")
    if maximum is not None and value > maximum:
        raise ValueError(f"{name} must be <= {maximum}")


@dataclass
class RecurseConfig:
    n: int = 6
    max_repeated_rejections: int = 2
    T: int = 3
    ladder: tuple[Tier, ...] = DEFAULT_LADDER
    halt_threshold: float = 0.9
    judge_model: str | None = None
    judge_votes: int = 1
    # A folding campaign may use scores for ranking, never for declaring a proof.
    judge_can_halt: bool = True
    compress_judge: bool = False
    compact_json_transport: bool = False  # measured lossless request framing only
    # Local prompt compression is active by default. No inference service is used.
    use_headroom: bool = True
    compression_backend: str = "local"  # local | headroom (already installed)
    compression_min_tokens: int = 256
    scratchpad_tokens: int = 1536
    context_tokens: int = 2048
    # Ceiling for visible system+user text. Reserve chat-template/output room separately.
    max_input_tokens: int | None = None
    token_counter: Any = None  # trusted local counter(text, model) -> int
    token_counter_label: str | None = None
    prose_compressor: Any = None
    pinned_notes: tuple[str, ...] = ()
    # Opt-in bounded archive/delta protocol; None preserves the v0.2 wire format.
    workspace: Any = None
    memory_auto_write: bool = True
    memory_session: Any = None  # host-bound optional user/project memory pipeline
    observation_ledger: Any = None  # host-recorded tool observations, never worker statuses
    memory_scope: str = "local"
    memory_max_bytes: int = 16_000_000
    memory_max_rounds: int = 2
    memory_read_chars: int = 12000
    # Model proposals select source records; only the controller has authority.
    enforce_progress: bool = True
    preseed_ladder: bool = True
    progress_k: int = 4
    progress_tokens: int = 1024
    progress_model: str | None = None
    progress_seed_mode: str = "model"  # model selection or local carry-forward
    reuse_exact_judgments: bool = False  # run-local snapshot; single-vote only
    progress_checks: tuple[Any, ...] = ()
    # Operator version for checker/corpus/custom-hook semantics on resume.
    verification_id: str = ""
    checkpoint_path: Any = None
    resume_from: Any = None
    validator: Validator | None = None
    oracle_sufficient: bool = True
    oracle_rung: int = 0
    oracle_note: str = ""
    feedback: Callable[[str], str] | None = None
    claim_audit: bool = False
    seed_scratchpad: str = ""
    seed_answer: str = ""
    retriever: Any = None
    audit_retriever: Any = None
    retrieval_k: int = 4
    retrieval_query_chars: int = 1200
    retrieval_max_chars: int = 8000
    temperature: float = 0.7
    # Count every attempted completion, including failures and judge retries.
    max_total_calls: int | None = None
    max_wall_seconds: float | None = None
    # Checker source generated by a model is not automatically executed.
    oracle_auto: bool = False
    oracle_model: str | None = None
    oracle_timeout_s: float = 10.0

    @classmethod
    def efficient(cls, *, budget: int = 4096, **overrides) -> "RecurseConfig":
        """Compact exact transport and local progress carry-forward. No new dependency.

        Does not change recurrence depth or permit compressed whole-proof judging.
        Explicit overrides win. A real tokenizer should be supplied by the host.
        """
        from .workspace import WorkspacePolicy
        values = dict(workspace=WorkspacePolicy(budget=budget, compact=True,
                      chunk_chars=768, max_optional_chunks=6),
                      progress_seed_mode="local", reuse_exact_judgments=True,
                      compact_json_transport=True)
        values.update(overrides)
        return cls(**values)

    @classmethod
    def for_workload(cls, workload: str, *, model="local", rungs=1, budget=4096, **overrides):
        """Explicit lighter schedules for interactive coding or evidence-led research.

        Rungs are budget ceilings, not independent models or discoveries. This
        opt-in helper does not alter the legacy constructor's recurrence.
        """
        if workload not in {"coding", "research"}:
            raise ValueError("workload must be coding or research")
        _integer("rungs", rungs)
        if rungs > 1000 or not isinstance(model,str) or not model.strip():
            raise ValueError("nonempty model and at most 1000 rungs required")
        from .workspace import WorkspacePolicy
        n=1 if workload=="coding" else 2
        values=dict(n=n,T=1,ladder=tuple(Tier(model,max_steps=1) for _ in range(rungs)),
                    max_total_calls=2+rungs*(3*(n+1)+2),judge_can_halt=workload!="research",
                    workspace=WorkspacePolicy(budget=budget,compact=True,enable_search=True,
                        chunk_chars=768,max_optional_chunks=6))
        values.update(overrides)
        cfg=cls.efficient(budget=budget,**values)
        cfg.validate()
        return cfg

    @classmethod
    def simple(cls, *, model="local", workload="coding", rungs=1, budget=4096, **overrides):
        """One proposal per step; arithmetic and acceptance stay in host callbacks."""
        from dataclasses import replace
        overrides.setdefault("n", 0)
        cfg = cls.for_workload(workload, model=model, rungs=rungs, budget=budget, **overrides)
        cfg.workspace = replace(cfg.workspace, typed_actions=True)
        cfg.validate()
        return cfg

    def steps_for(self, tier: Tier) -> int:
        return tier.max_steps if tier.max_steps is not None else self.T

    def validate(self) -> None:
        _integer("n", self.n, minimum=0)
        _integer("max_repeated_rejections", self.max_repeated_rejections)
        _integer("T", self.T)
        if not isinstance(self.ladder, (tuple, list)) or not self.ladder:
            raise ValueError("ladder must contain at least one Tier")
        for tier in self.ladder:
            if not isinstance(tier, Tier) or not isinstance(tier.model, str) or not tier.model.strip():
                raise ValueError("every tier must have a nonempty model identifier")
            if tier.max_steps is not None:
                _integer("max_steps", tier.max_steps)
            _integer("max_tokens", tier.max_tokens)
            if tier.step_timeout_s is not None:
                _number("step_timeout_s", tier.step_timeout_s, strict=True)
        if self.judge_model is not None and (not isinstance(self.judge_model, str) or not self.judge_model.strip()):
            raise ValueError("judge_model must be a nonempty string")
        _number("halt_threshold", self.halt_threshold, maximum=1, strict=True)
        _number("temperature", self.temperature, maximum=1)
        _integer("judge_votes", self.judge_votes)
        if self.progress_seed_mode not in {"model", "local"}:
            raise ValueError("progress_seed_mode must be model or local")
        if type(self.reuse_exact_judgments) is not bool:
            raise TypeError("reuse_exact_judgments must be a bool")
        for name in ("retrieval_k", "retrieval_query_chars", "retrieval_max_chars"):
            _integer(name, getattr(self, name))
        if self.max_total_calls is not None:
            _integer("max_total_calls", self.max_total_calls)
        if self.max_wall_seconds is not None:
            _number("max_wall_seconds", self.max_wall_seconds, strict=True)
        _number("oracle_timeout_s", self.oracle_timeout_s, strict=True)
        for name in ("seed_answer", "seed_scratchpad", "oracle_note"):
            if not isinstance(getattr(self, name), str):
                raise TypeError(f"{name} must be a string")
        for name in ("use_headroom", "compress_judge", "oracle_sufficient", "claim_audit", "oracle_auto", "enforce_progress", "preseed_ladder", "judge_can_halt", "memory_auto_write"):
            if type(getattr(self, name)) is not bool:
                raise TypeError(f"{name} must be a bool")
        if self.workspace is not None:
            from .workspace import WorkspacePolicy
            if not isinstance(self.workspace, WorkspacePolicy):
                raise TypeError("workspace must be a WorkspacePolicy")
            self.workspace.validate()
            if self.compress_judge:
                raise ValueError("workspace mode requires exact full judge inputs")
        if type(self.compact_json_transport) is not bool:
            raise TypeError("compact_json_transport must be bool")
        if self.workspace is not None and self.workspace.solve_map and self.memory_session is None:
            raise ValueError("solve-map requires an explicitly scoped memory session")
        if self.memory_session is not None:
            from .memory import MemorySession
            if not isinstance(self.memory_session, MemorySession):
                raise TypeError("memory_session must be host-bound MemorySession")
            if self.workspace is None or not self.workspace.compact or not self.workspace.enable_search:
                raise ValueError("memory integration requires searchable compact workspace")
            if not self.verification_id:
                raise ValueError("memory integration requires explicit verification_id")
        if self.observation_ledger is not None:
            from .memory.observations import ObservationLedger
            if not isinstance(self.observation_ledger, ObservationLedger) or self.memory_session is None:
                raise ValueError("observations require a host-bound memory session")
            if self.observation_ledger.principal != self.memory_session.principal or self.observation_ledger.store is not self.memory_session.store:
                raise ValueError("observation/session principal mismatch")
        if self.validator is not None and not callable(self.validator):
            raise TypeError("validator must be callable")
        if self.feedback is not None and not callable(self.feedback):
            raise TypeError("feedback must be callable")
        if self.oracle_auto:
            raise ValueError("automatic execution of generated checkers is disabled; provide a reviewed validator")

        for name in ("scratchpad_tokens", "context_tokens", "compression_min_tokens",
                     "progress_k", "progress_tokens", "memory_max_bytes", "memory_read_chars"):
            _integer(name, getattr(self, name))
        _integer("memory_max_rounds", self.memory_max_rounds, minimum=0)
        if self.max_input_tokens is not None:
            _integer("max_input_tokens", self.max_input_tokens)
        if self.compression_backend not in {"local", "headroom"}:
            raise ValueError("compression_backend must be local or headroom")
        if self.token_counter is not None and not callable(self.token_counter):
            raise TypeError("token_counter must be callable")
        if self.token_counter_label is not None and (not isinstance(self.token_counter_label, str) or not self.token_counter_label):
            raise ValueError("token_counter_label must be nonempty text")
        if self.prose_compressor is not None and not callable(getattr(self.prose_compressor, "compress", None)):
            raise TypeError("prose_compressor must expose compress")
        if self.prose_compressor is not None and self.compression_backend != "local":
            raise ValueError("choose the built-in Headroom adapter or a custom compressor, not both")
        if not isinstance(self.pinned_notes, tuple) or any(not isinstance(t, str) or not t for t in self.pinned_notes):
            raise ValueError("pinned_notes must be a tuple of nonempty exact strings")
        if not isinstance(self.memory_scope, str) or not self.memory_scope.strip():
            raise ValueError("memory_scope must be nonempty")
        if not isinstance(self.verification_id, str):
            raise TypeError("verification_id must be text")
        if self.progress_model is not None and self.progress_model not in {tier.model for tier in self.ladder}:
            raise ValueError("progress_model must name an operator-selected ladder model")
        from .progress import ProgressCheck
        if (not isinstance(self.progress_checks, tuple) or
                any(not isinstance(c, ProgressCheck) for c in self.progress_checks) or
                len({c.name for c in self.progress_checks}) != len(self.progress_checks)):
            raise ValueError("progress_checks must be a tuple of uniquely named ProgressChecks")
        if self.progress_checks and not self.enforce_progress:
            raise ValueError("progress checks require enforce_progress=True")
        if (self.checkpoint_path or self.resume_from) and (
                self.validator or self.progress_checks or self.retriever or self.audit_retriever or
                self.feedback or self.prose_compressor or self.token_counter) and not self.verification_id:
            raise ValueError("checkpointing custom checks/hooks requires an explicit verification_id")
