"""Bind externally issued folding admissions to the real Headroom refinement loop.

All historical bytes remain exact. New admitted records are exact registry records,
not arbitrary prose or statuses generated by a worker. Each new record earns its
own progress lock; removing one is rejected before a model judge is consulted.
"""
from __future__ import annotations
from dataclasses import replace
from .types import FoldError, canonical, decode, sha
from ..config import RecurseConfig
from ..progress import ProgressCheck
from ..workspace import WorkspacePolicy

MARKER="\n\nFOLDING ADMISSIONS V1\n"


class ResearchBridge:
    def __init__(self, folding, history: str, admissions: tuple[str,...]):
        if type(history) is not str or not history.strip() or MARKER in history:
            raise FoldError("nonempty unambiguous history required")
        if type(admissions) is not tuple or any(type(r)is not str for r in admissions) or len(set(admissions)) != len(admissions):
            raise FoldError("admission IDs must be unique")
        self.folding=folding
        self.history=history
        self.history_hash=sha(history.encode())
        self.records={r:folding.admission(r) for r in admissions}
        self.policy_id=sha(canonical({"policy":folding.state["policy"],"history":self.history_hash,
                                     "admissions":sorted(self.records)}))

    def render(self, selected: tuple[str,...]) -> str:
        if any(r not in self.records for r in selected) or len(set(selected))!=len(selected):
            raise FoldError("unknown or duplicate admission")
        if not selected:
            return self.history
        records=[{"id":r,"record":self.records[r]}for r in selected]
        return self.history+MARKER+canonical(records).decode()

    def parse(self, answer: str) -> tuple[str,...]:
        if answer==self.history:
            return ()
        if not answer.startswith(self.history+MARKER):
            raise FoldError("historical evidence changed")
        raw=answer[len(self.history+MARKER):]
        obj=decode(raw)
        if type(obj) is not list:
            raise FoldError("invalid admissions envelope")
        refs=[]
        for item in obj:
            if type(item) is not dict or set(item)!={"id","record"} or type(item["id"])is not str:
                raise FoldError("malformed admission")
            ref=item["id"]
            if ref not in self.records or item["record"]!=self.folding.admission(ref):
                raise FoldError("unissued, modified, or cross-scope admission")
            refs.append(ref)
        if len(set(refs))!=len(refs) or self.render(tuple(refs))!=answer:
            raise FoldError("noncanonical or duplicate admission")
        return tuple(refs)

    def valid(self, answer: str) -> bool:
        try:
            self.parse(answer)
            return True
        except Exception:
            return False

    def contains(self, answer: str, ref: str) -> bool:
        try:
            return ref in self.parse(answer)
        except Exception:
            return False

    def admit_checked(self, current: str, refs: tuple[str, ...], *, progress_checks=()):
        """Host-only exact record ingestion; zero model review, zero proof promotion.

        The unchanged history and every old/new admission are checked against the
        trusted registry. This is not a substitute for generative research or a
        whole-proof review. Scope is intentionally present in the return value.
        """
        prior=self.parse(current)
        if type(refs) is not tuple or any(type(r) is not str for r in refs) or len(set(refs))!=len(refs):
            raise FoldError("admission IDs must be unique")
        if set(refs)&set(prior):
            raise FoldError("admission already present")
        updated=self.render(prior+refs)
        self.parse(updated)
        for check in progress_checks:
            if check.check(updated) is not True:
                raise FoldError("external progress check rejected exact admission")
        return {"answer":updated,"answer_hash":sha(updated.encode()),"added":list(refs),
                "coverage":"exact issued records and unchanged history only",
                "whole_proof_reviewed":False,"settles_target":False,"model_calls":0}

    def bind(self, cfg: RecurseConfig, *, workspace_budget: int = 4096) -> RecurseConfig:
        checks=(ProgressCheck("fold-envelope-"+self.policy_id[:16],
                     "Preserve the exact archived history and admit only externally checked folding records; no model promotion.",
                     self.valid,required=True),)
        checks+=tuple(ProgressCheck("fold-record-"+r[:32],
                     "Retain this scoped externally issued record: "+r,
                     lambda a,r=r:self.contains(a,r)) for r in self.records)
        workspace=cfg.workspace or WorkspacePolicy(budget=workspace_budget)
        return replace(cfg,seed_answer=self.history if not cfg.resume_from else "",
                       progress_checks=tuple(cfg.progress_checks)+checks,workspace=workspace,
                       enforce_progress=True,compress_judge=False,judge_can_halt=False,
                       # Finite results or empirical promotions never settle the grand target.
                       oracle_sufficient=False,
                       # Confirmation-bearing admissions must not seed future generation memory.
                       memory_auto_write=False,
                       verification_id=cfg.verification_id+"/fold-"+self.policy_id,
                       memory_scope=self.folding.scope)
